### ISSUE TITLE
add url and name of pics in imageslider

### ISSUE THREAD

**Issue by mhkhajehpoor** [smarteist/Android-Image-Slider#1]
Hi. Thank you for the library. I want to use VOLLEY to get the image address and description for each image from JESON and add it to SwitchCase. How should I do that?
Thank you for your help

**Comment by Paridel** [comment]
`private List<String> stringList;

JsonArrayRequest jsonArrayRequest = new JsonArrayRequest(Request.Method.GET, URL, null,
                new Response.Listener<JSONArray>() {
                    @Override
                    public void onResponse(JSONArray response) {
                        stringList = new ArrayList<>();
                        try {
                            else {
                                for(int i=0;i<response.length();i++){

                                    JSONObject object = response.getJSONObject(i);

                                    String avatar = object.getString("avatar");
                                    stringList.add(avatar);

                                    SliderView sliderView = new SliderView(getApplicationContext());
                                    sliderView.setImageUrl(String.valueOf(stringList.get(i)));
                                    sliderView.setImageScaleType(ImageView.ScaleType.CENTER_CROP);
                                    sliderLayout.addSliderView(sliderView);
                                }
                            }

                        }
                        catch (JSONException e){
                            e.printStackTrace();
                        }
                    }
                });
        RequestQueue requestQueue = Volley.newRequestQueue(getApplicationContext());
        requestQueue.add(jsonArrayRequest);`

**Comment by Paridel** [comment]
private List<String> stringList;

JsonArrayRequest jsonArrayRequest = new JsonArrayRequest(Request.Method.GET, URL, null,
                new Response.Listener<JSONArray>() {
                    @Override
                    public void onResponse(JSONArray response) {
                        stringList = new ArrayList<>();
                        try {
                            else {
                                for(int i=0;i<response.length();i++){

                                    JSONObject object = response.getJSONObject(i);

                                    String avatar = object.getString("avatar");
                                    stringList.add(avatar);

                                    SliderView sliderView = new SliderView(getApplicationContext());
                                    sliderView.setImageUrl(String.valueOf(stringList.get(i)));
                                    sliderView.setImageScaleType(ImageView.ScaleType.CENTER_CROP);
                                    sliderLayout.addSliderView(sliderView);
                                }
                            }

                        }
                        catch (JSONException e){
                            e.printStackTrace();
                        }
                    }
                });
        RequestQueue requestQueue = Volley.newRequestQueue(getApplicationContext());
        requestQueue.add(jsonArrayRequest);

**Comment by Paridel** [comment]
private List<String> stringList;

        JsonArrayRequest jsonArrayRequest = new JsonArrayRequest(Request.Method.GET, URL, null,
                new Response.Listener<JSONArray>() {
                    @Override
                    public void onResponse(JSONArray response) {
                        Log.d("", response.toString());
                        stringList = new ArrayList<>();
                        try {
                            if (response.length() == 0){
                                Snackbar.make(containerView, getString(R.string.item_empty), Snackbar.LENGTH_LONG).show();
                            }
                            else {
                                for(int i=0;i<response.length();i++){

                                    Log.d("", String.valueOf(response.length()));
                                    JSONObject object = response.getJSONObject(i);

                                    String avatar = object.getString("avatar");
                                    stringList.add(avatar);

                                    SliderView sliderView = new SliderView(getApplicationContext());
                                    sliderView.setImageUrl(String.valueOf(stringList.get(i)));
                                    sliderView.setImageScaleType(ImageView.ScaleType.CENTER_CROP);
                                    sliderLayout.addSliderView(sliderView);

                                }
                            }

                        }
                        catch (JSONException e){
                            e.printStackTrace();
                        }
                    }
                },
                new Response.ErrorListener() {
                    @Override
                    public void onErrorResponse(VolleyError error) {
                        
                    }
                });
        RequestQueue requestQueue = Volley.newRequestQueue(getApplicationContext());
        requestQueue.add(jsonArrayRequest);

**Comment by mhkhajehpoor** [comment]
tanx
