### ISSUE TITLE
Remove inner shadow 

### ISSUE THREAD

**Issue by rm808022** [smarteist/Android-Image-Slider#10]
I want to remove inner shadow which comes at the bottom of the image, so please help me with that.
You can see inner shadow at the bottom of the image in the given below link.
https://github.com/smarteist/android-image-slider/blob/master/1.gif

Thank You..!!

**Comment by Deepak111992** [comment]
have you found somthing?

**Comment by rm808022** [comment]
Nope

**Comment by Deepak111992** [comment]
ok

**Comment by siteantipas** [comment]
Hi there, I'm facing this problem just some weeks after you.
Any one has got the solution to removing the bottom shadow?
Thank you

**Comment by Jejid** [comment]
Nothing yet? ='( it can be a nice enhancement

**Comment by ajaygosh102** [comment]
yah, you can edit it in external library layout.

you can find image_slider_layout_item.xml

just set this overlay visibility as gone.

<FrameLayout
        android:visibility="gone"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom"
        android:background="@drawable/bg_overlay">

**Comment by Typ6uHa** [comment]
I sended pull Request with new method to show/hide shadow

**Comment by tamtom** [comment]
You can check this library https://github.com/OpenSooq/Pluto
it has the ability to have full control over your views and layout

**Comment by AmirMehr** [comment]
I changed SliderAdapter and now it is ok


`
public class SliderAdapter extends SliderViewAdapter<SliderAdapter.SliderAdapterVH> {

    private Context context;
    private List<SliderItem> mSliderItems = new ArrayList<>();
    private boolean withBottomGradient;

    public SliderAdapter (Context context, boolean withBottomGradient) {
        this.withBottomGradient = withBottomGradient;
        this.context = context;
    }

    public void renewItems(List<SliderItem> sliderItems) {
        this.mSliderItems = sliderItems;
        notifyDataSetChanged();
    }

    public void deleteItem(int position) {
        this.mSliderItems.remove(position);
        notifyDataSetChanged();
    }

    public void addItem(SliderItem sliderItem) {
        this.mSliderItems.add(sliderItem);
        notifyDataSetChanged();
    }

    @Override
    public SliderAdapterVH onCreateViewHolder(ViewGroup parent) {
        View inflate = LayoutInflater.from(parent.getContext()).inflate(R.layout.image_slider_layout_item, null);
        FrameLayout bottomGradient = inflate.findViewById(R.id.fl_shadow_container);
        if(!withBottomGradient){
            bottomGradient.setBackgroundResource(0);
        }
        return new SliderAdapterVH(inflate);
    }

    @Override
    public void onBindViewHolder(SliderAdapterVH viewHolder, final int position) {

        SliderItem sliderItem = mSliderItems.get(position);

        viewHolder.textViewDescription.setText(sliderItem.getText());
        viewHolder.textViewDescription.setTextSize(16);
        viewHolder.textViewDescription.setTextColor(Color.WHITE);
        CircularProgressDrawable circularProgressDrawable = new CircularProgressDrawable(context);
        circularProgressDrawable.setStrokeWidth(5f);
        circularProgressDrawable.setCenterRadius(30f);
        circularProgressDrawable.setColorSchemeColors(context.getResources().getColor(R.color.colorGray));
        circularProgressDrawable.start();
        Glide.with(viewHolder.itemView)
        .load(sliderItem.getImage()).apply(new RequestOptions()
                .placeholder(circularProgressDrawable)
                .fitCenter())
        .fitCenter()
        .into(viewHolder.imageViewBackground);

        viewHolder.itemView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
               // Toast.makeText(context, "This is item in position " + position, Toast.LENGTH_SHORT).show();
            }
        });
    }

    @Override
    public int getCount() {
            //slider view count could be dynamic size
            return mSliderItems.size();
            }

    class SliderAdapterVH extends SliderViewAdapter.ViewHolder {

        View itemView;
        ImageView imageViewBackground;
        ImageView imageGifContainer;
        TextView textViewDescription;

        public SliderAdapterVH(View itemView) {
            super(itemView);
            imageViewBackground = itemView.findViewById(R.id.iv_auto_image_slider);
            imageGifContainer = itemView.findViewById(R.id.iv_gif_container);
            textViewDescription = itemView.findViewById(R.id.tv_auto_image_slider);
            this.itemView = itemView;
        }
    }

}`

**Comment by das1192** [comment]
> 
> 
> yah, you can edit it in external library layout.
> 
> you can find image_slider_layout_item.xml
> 
> just set this overlay visibility as gone.

cool mate
