### ISSUE TITLE
Click listener in adapter return only single position

### ISSUE THREAD

**Issue by Nightttttttttt** [smarteist/Android-Image-Slider#100]
I try solutions in **Issues** and does not improve ..
i only get last position of slide..
Eg. Toast only show position 3 on every 4 slides...

P.S
Slider is really impressive

**Comment by smarteist** [comment]
Take a [look at the "adapter" example](https://github.com/smarteist/Android-Image-Slider/blob/master/app/src/main/java/com/smarteist/imageslider/SliderAdapterExample.java), if u want to set a listener for slider use `sliderview.setCurrentPageListener()` .

**Comment by Nightttttttttt** [comment]
Thanks work like a charm!
