### ISSUE TITLE
Kotlin! Can you put how to do in Kotlin

### ISSUE THREAD

**Issue by joaogarrido98** [smarteist/Android-Image-Slider#102]
Please explain how to do in kotlin

**Comment by smarteist** [comment]
> Please explain how to do in kotlin

Kotlin have interoperability with java , so you can use this lib in kotlin projects.
In the future we will migrate the codes to kotlin, and we will also write test for this project.

**Comment by joaogarrido98** [comment]
But how do I use the code you have to kotlin? I'm new to this android thing
