### ISSUE TITLE
Active indicator always start at 2

### ISSUE THREAD

**Issue by leosird** [smarteist/Android-Image-Slider#108]
Hi, @smarteist please help me.
I have a problem when the first load, active indicator starts at 2nd. The order of the images is totally fine. It happens only for the first image.

I put configuration inside fragment method `onViewCreated`: [Here is sample code](https://gist.github.com/leosird/9abb3ba19d5923ffdf57199cc9e8c9ac)

**Additional info**
I am using Kotlin with Glide, LiveData and Coroutines

**Screenshots**
Wrong result:
![image](https://user-images.githubusercontent.com/16789007/74922537-f1674980-5401-11ea-9b51-d6ce7bbce339.png)

Expected result:
![image](https://user-images.githubusercontent.com/16789007/74923456-638c5e00-5403-11ea-99c6-e0cb017d84bf.png)

**Comment by smarteist** [comment]
> Hi, @smarteist please help me.
> I have a problem when the first load, active indicator starts at 2nd. The order of the images is totally fine. It happens only for the first image.
> 
> I put configuration inside fragment method `onViewCreated`: [Here is sample code](https://gist.github.com/leosird/9abb3ba19d5923ffdf57199cc9e8c9ac)
> 
> **Additional info**
> I am using Kotlin with Glide, LiveData and Coroutines
> 
> **Screenshots**
> Wrong result:
> ![image](https://user-images.githubusercontent.com/16789007/74922537-f1674980-5401-11ea-9b51-d6ce7bbce339.png)
> 
> Expected result:
> ![image](https://user-images.githubusercontent.com/16789007/74923456-638c5e00-5403-11ea-99c6-e0cb017d84bf.png)

Thank you for reporting this bug , now i fixed it and please update.

**Comment by rashid56156** [comment]
The bug is fixed now. Thanks
