### ISSUE TITLE
How can stop infinite adapter?

### ISSUE THREAD

**Issue by developerGM** [smarteist/Android-Image-Slider#116]
With release 1.3.5 I cannot use `app:sliderCircularHandlerEnabled="boolean"` but I want that slider, if it has 4 images, stop on 4th image and not go next in a infinite mode.
How can I do ?

**Comment by ArslanYasin** [comment]
i also want this

**Comment by m-melis** [comment]
I've downgraded to version 1.3.3 to use `setCircularHandlerEnabled(false)`. Should be added back hopefully.

**Comment by smarteist** [comment]
> With release 1.3.5 I cannot use `app:sliderCircularHandlerEnabled="boolean"` but I want that slider, if it has 4 images, stop on 4th image and not go next in a infinite mode.
> How can I do ?

Checkout version ```1.3.6``` , and pass boolean false for second arg in ```sliderView.setAdapter()``` method.
