### ISSUE TITLE
how to disable slider if there is only one image

### ISSUE THREAD

**Issue by MoustafaElsaghier** [smarteist/Android-Image-Slider#124]
**Describe the bug**
I've only one image in my slider for special cases but, the user still can swipe in the slider, how can I make it not swipe if only one image there?

**Comment by m-melis** [comment]
Downgrade to version 1.3.3 and use `setCircularHandlerEnabled(false)`. I hope they add this option back.

**Comment by smarteist** [comment]
Updated , checkout ```1.3.6``` , and pass boolean false for ```sliderView.setAdapter()``` method.
