### ISSUE TITLE
Can we add slideToPreviousPosition API?

### ISSUE THREAD

**Issue by itechevo** [smarteist/Android-Image-Slider#126]
There is a slideToNextPosition API. Can we add slideToPreviousPosition?

public void slideToPreviousPosition() {

        int currentPosition = mSliderPager.getCurrentItem();
        int adapterItemsCount = getAdapterItemsCount();

        if (mAutoCycleDirection == AUTO_CYCLE_DIRECTION_BACK_AND_FORTH && adapterItemsCount > 1) {
            if (currentPosition % (adapterItemsCount - 1) == 0) {
                mFlagBackAndForth = !mFlagBackAndForth;
            }
            if (mFlagBackAndForth) {
                mSliderPager.setCurrentItem(--currentPosition, true);
            } else {
                mSliderPager.setCurrentItem(++currentPosition, true);
            }
        } else if (mAutoCycleDirection == AUTO_CYCLE_DIRECTION_LEFT) {
            mSliderPager.setCurrentItem(++currentPosition, true);
        } else {
            mSliderPager.setCurrentItem(--currentPosition, true);
        }
    }

**Comment by smarteist** [comment]
> There is a slideToNextPosition API. Can we add slideToPreviousPosition?
> 
> public void slideToPreviousPosition() {
> 
> ```
>     int currentPosition = mSliderPager.getCurrentItem();
>     int adapterItemsCount = getAdapterItemsCount();
> 
>     if (mAutoCycleDirection == AUTO_CYCLE_DIRECTION_BACK_AND_FORTH && adapterItemsCount > 1) {
>         if (currentPosition % (adapterItemsCount - 1) == 0) {
>             mFlagBackAndForth = !mFlagBackAndForth;
>         }
>         if (mFlagBackAndForth) {
>             mSliderPager.setCurrentItem(--currentPosition, true);
>         } else {
>             mSliderPager.setCurrentItem(++currentPosition, true);
>         }
>     } else if (mAutoCycleDirection == AUTO_CYCLE_DIRECTION_LEFT) {
>         mSliderPager.setCurrentItem(++currentPosition, true);
>     } else {
>         mSliderPager.setCurrentItem(--currentPosition, true);
>     }
> }
> ```

Updated ```1.3.6```.
