### ISSUE TITLE
Add InfinityEnabled boolean feature

### ISSUE THREAD

**Issue by baudelioandalon** [smarteist/Android-Image-Slider#127]
I have this request because when i added lottie animation into slider, this animation will stops in the 3 position and when i back problem still

**solution**
I had downgrade to 1.3.3 version and use sliderView.setCircularHandlerEnabled(false);

**Alternative**
Add InfinityEnabled boolean feature

**Comment by smarteist** [comment]
Updated , checkout ```1.3.6``` , and pass boolean false for ```sliderView.setAdapter()``` method.
