### ISSUE TITLE
Clear sliderViews from SliderLayout

### ISSUE THREAD

**Issue by guilhermehmcarvalho** [smarteist/Android-Image-Slider#13]
Requesting a feature to clear the sliderViews contained within a SliderLayout.
This'd be a necessary feature to use the Slider on a RecycleView's row, for instance.

**Comment by sathishmscict** [comment]
Add below code in : SliderAdapter.java
public void removeAllSliderViews() {
        if (BuildConfig.DEBUG) {
            Log.d(TAG, "removeAllSliderViews called");
        }
        sliderViews.clear();
        notifyDataSetChanged();
    }
    public int getItemPosition(Object object) {
        return POSITION_NONE;
    }


Add below code in :  SliderLayout.java
public void removeAllSliderView() {
        ((SliderAdapter) mFlippingPagerAdapter).removeAllSliderViews();
    }


Add below code, where you want remove;
SliderLayout imageSlider = findViewById(R.id.imageSlider);
imageSlider.removeAllSliderView();

Above am implemented and working fine.

**Comment by VAO-PL** [comment]
Yes, I wrote this feature and it was merged into the project already but the thread was open before this. Maybe it should be closed now.
