### ISSUE TITLE
how to passing image url from slider to other activity?

### ISSUE THREAD

**Issue by firecatmusic** [smarteist/android-image-slider#15]
i was trying to pass image url from setOnSliderListener and return null,
can someone help me?

here my code

        for (i in 0..3) {

            val sliderView = SliderView(ctx)

            when (i) {
                0 -> sliderView.imageUrl = "https://images.pexels.com/photos/547114/pexels-photo-547114.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260"
                1 -> sliderView.imageUrl = "https://images.pexels.com/photos/218983/pexels-photo-218983.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260"
                2 -> sliderView.imageUrl = "https://images.pexels.com/photos/747964/pexels-photo-747964.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260"
                3 -> sliderView.imageUrl = "https://images.pexels.com/photos/929778/pexels-photo-929778.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260"
            }

            sliderView.setImageScaleType(ImageView.ScaleType.CENTER_CROP)
            sliderView.setDescription("setDescription " + (i + 1))
            sliderView.setOnSliderClickListener {
                startActivity<DetailSliderActivity>(
                        "imageSliderUrl" to i
                )
            }

            //at last add this view in your layout :
            slider.addSliderView(sliderView)
        }

**Comment by Jejid** [comment]
Hi im not a pro but u can use an array Url container. when u call the click listener u take array[i] for intent. at least in java i did it. Somethig like this. ( other image slider very similar to this) 

private void setLayoutFlipper() {

        Establecimiento [] estaPagos = RetornosVarios.getTodosPremium(0);

        for ( int i =0;i <estaPagos.length;i++){
            FlipperView view = new FlipperView(getActivity());
            view.setImageDrawable(estaPagos[i].getImagen());
            view.setImageScaleType(ImageView.ScaleType.FIT_CENTER);

            final Establecimiento establecimientoClicked = estaPagos[i]; // here i take array position
            view.setOnFlipperClickListener(new FlipperView.OnFlipperClickListener() {
                @Override
                public void onFlipperClick(FlipperView flipperView) {
                    Intent intent = new Intent(getActivity(),EstablecimientoActivity.class);
                    intent.putExtra("Establecimiento a Abrir", establecimientoClicked);
                    startActivity(intent);
                }
            });
            //flipper.addFlipperView(view);
            //flipper.setScrollTimeInSec(5);
        }
    }

..hope it help u something
