### ISSUE TITLE
Add new Option

### ISSUE THREAD

**Issue by ZeeshanArid** [smarteist/Android-Image-Slider#16]
Add new option to hide indicator

**Comment by HussainSatham** [comment]
Is there any way to hide the indicator?

**Comment by firecatmusic** [comment]
@HussainSatham, have you try to add app:indicator_visibility in the xml?

**Comment by tamtom** [comment]
You can check this library https://github.com/OpenSooq/Pluto
it has the ability to have full control over your views and layout and many specs of indicator
