### ISSUE TITLE
7 or More Images Breaks the Slider

### ISSUE THREAD

**Issue by AlmutawaEssam** [smarteist/Android-Image-Slider#168]
**Describe the bug**
When having 7 or more images in the slider, the slider starts at a different position than 0, and sometimes it breaks the slide direction so it goes from right to left rather than from left to right,

**To Reproduce**
1. Add 7 images to the slider

**Expected behavior**
Starts at index 0 and remains sliding from left to right 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Samsung S20 Ultra
 - OS: Android 10
 - Browser Chrome

**Additional context**

**Comment by AlmutawaEssam** [comment]
To solve this issue,
I am using a workaround: getSliderPager().setCurrentItem(0,true)

**Comment by gmMustafa** [comment]
Hey, I am still facing the same issue, I have 7 images in the slider view. it is working fine for less than 7 images.


```
  List<Image> shirtImageUrls = CommonVars.singleProductDetailViewer.getProductDetails().getLocal_images();
 adapter = new

                ProductPicturesAdapter(ProductDetails.this, shirtImageUrls, getSupportFragmentManager());
        // below method is used to set auto cycle direction in left to
        // right direction you can change according to requirement.
        productSliderView.setAutoCycleDirection(SliderView.LAYOUT_DIRECTION_LTR);

        // below method is used to
        // setadapter to sliderview.
        productSliderView.setSliderAdapter(adapter);


        // below method is use to set
        // scroll time in seconds.
        productSliderView.setScrollTimeInSec(3);

        // to set it scrollable automatically
        // we use below method.
        productSliderView.setAutoCycle(true);

        // to start autocycle below method is used.
        productSliderView.startAutoCycle();
        
        // i have tried the below approach but it is also not working out.
        productSliderView.getSliderPager().setCurrentItem(0,true);
```
