### ISSUE TITLE
I can't stop auto scroll image ? Help please

### ISSUE THREAD

**Issue by mabubeo** [smarteist/Android-Image-Slider#17]

**Comment by milindbl** [comment]
Same issue here, would love the ability to stop autoscroll.

**Comment by rajscet** [comment]
sliderLayout.setScrollTimeInSec(10000000); its working

**Comment by milindbl** [comment]
I ended up cloning the project as I found a few other bugs and disabled autoscroll by default.

**Comment by tamtom** [comment]
You can check this library https://github.com/OpenSooq/Pluto
it has the ability to have full control over your views and layout and disabling/enabling the auto scroll is very easy
