### ISSUE TITLE
Auto Sliding Still have issue with 11 Items

### ISSUE THREAD

**Issue by Pushpendracolourmoon** [smarteist/Android-Image-Slider#177]
**Describe the bug**
When I am trying to implement this Library in my application. So I have found that Auto Scrolling issue with 11 items. Then I have try to reduce the number of images from banner and it worked fine with 8 images. So It's randomly happening some time start from position 4 and directly reached to position 8. And after that it's keep sliding randomly. Please let me know the stable solution for this issue as soon as possible. Because I like this library and I do not want to jump to another option.

**To Reproduce**
1. Add 11 images in SlideItem
2. Run the application
3. And check the output

**Expected behavior**
Whenever auto slide is enable. It should slide one by one image of the slide. That's only should happen.

**Screenshots**
[https://drive.google.com/file/d/1n76VkSGw4q4NvF2wOjY_GkcniEmDlkc4/view?usp=sharing] Drive Link

**Desktop (please complete the following information):**
 - OS: MacBook Pro
 - Browser safari
 - Version 14

**Smartphone (please complete the following information):**
 - Device: Motorola
 - OS: Android 7

**Additional context**
I am using the following library
implementation 'com.github.smarteist:autoimageslider:1.3.9-appcompat'

**Comment by smarteist** [comment]
> **Describe the bug**
> When I am trying to implement this Library in my application. So I have found that Auto Scrolling issue with 11 items. Then I have try to reduce the number of images from banner and it worked fine with 8 images. So It's randomly happening some time start from position 4 and directly reached to position 8. And after that it's keep sliding randomly. Please let me know the stable solution for this issue as soon as possible. Because I like this library and I do not want to jump to another option.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Add 11 images in SlideItem
> 2. Run the application
> 3. And check the output
> 
> **Expected behavior**
> Whenever auto slide is enable. It should slide one by one image of the slide. That's only should happen.
> 
> **Screenshots**
> [https://drive.google.com/file/d/1n76VkSGw4q4NvF2wOjY_GkcniEmDlkc4/view?usp=sharing] Drive Link
> 
> **Desktop (please complete the following information):**
> 
> * OS: MacBook Pro
> * Browser safari
> * Version 14
> 
> **Smartphone (please complete the following information):**
> 
> * Device: Motorola
> * OS: Android 7
> 
> **Additional context**
> I am using the following library
> implementation 'com.github.smarteist:autoimageslider:1.3.9-appcompat'

This bug fixed now plz update 1.4.0
