### ISSUE TITLE
cannot resolve symbol 'Animations' inside (SliderLayout.Animations.FILL) why?

### ISSUE THREAD

**Issue by Rahvayana** [smarteist/Android-Image-Slider#19]
i just try to copy+ and paste your code to mine but this is happen cannot resolve symbol 'Animations'

**Comment by DanishRafique** [comment]
https://github.com/smarteist/android-image-slider/blob/master/app/src/main/java/com/smarteist/imageslider/MainActivity.java

**Comment by knightcube** [comment]
Use `IndicatorAnimations.FILL` instead of `SliderLayout.Animations.FILL`
