### ISSUE TITLE
How to disable auto scrolling?

### ISSUE THREAD

**Issue by THamza** [smarteist/Android-Image-Slider#2]

**Comment by venky97vp** [comment]
This issue is solved here #7 
You can use `sliderLayout.enableAutoScrolling(false);` in java or
`app:piv_enable_auto_scrolling = "true"` in xml

**Comment by khurram33250** [comment]
This is not working with current version.

**Comment by venky97vp** [comment]
Sorry! My pull request is not merged with the master branch by the author yet. If you want you can pull the code and use it ;)

**Comment by smarteist** [comment]
Checkout 1.3.0
