### ISSUE TITLE
Implement into recyclerview element

### ISSUE THREAD

**Issue by RizhoX** [smarteist/android-image-slider#200]
I want to know how to implement this library into my recyclerview like the gif below, with diferent images from server per element

![Hnet-image](https://user-images.githubusercontent.com/77412603/115058805-d9267980-9ea2-11eb-82b2-b2f178466468.gif)

**Comment by Eleftheria-99** [comment]
no need to use a recyclerview, just create a loist with Uri's in SLiderViewAdapter and in every page of the dapter show an image
