### ISSUE TITLE
how to use in androidx?

### ISSUE THREAD

**Issue by arjava** [smarteist/Android-Image-Slider#21]
I use androidx and there are some missing errors like the following :
> Cannot access '<init>': it is public/*package*/ in 'SliderView'

**Comment by rockbass2560** [comment]
@arjava Maybe you have to use legacy support library in your project

implementation 'androidx.legacy:legacy-support-v4:1.0.0'

**Comment by smarteist** [comment]
Hi , new version 1.3.0 now supports androidx components .
