### ISSUE TITLE
Received status code 401 from server: Unauthorized

### ISSUE THREAD

**Issue by misbahazmi** [smarteist/android-image-slider#215]
Could not GET 'https://jitpack.io/com/github/smarteist/autoimageslider/1.4.0/autoimageslider-1.4.0.pom'. Received status code 401 from server: Unauthorized

While building the project.

**Comment by zion830** [comment]
Did you recently update the Android studio version to 4.x.x?

**Comment by mona-baharlou** [comment]
> Did you recently update the Android studio version to 4.x.x?

I updated the Android Studio to Arctic version. What is the solution?

**Comment by IrhamMaulani** [comment]
Have the same problem. Adding jcenter inside repositories in build.grade can temporarily fix it

**Comment by misbahazmi** [comment]
> Did you recently update the Android studio version to 4.x.x?

Yes, Arctic Version

**Comment by zion830** [comment]
> > Did you recently update the Android studio version to 4.x.x?
> 
> Yes, Arctic Version

I had the same problem after updating android studio
I guess its because this library doesn't use mavenCentral in build.gradle

**Comment by stutijain314** [comment]
> > Did you recently update the Android studio version to 4.x.x?
> 
> Yes, Arctic Version

Did u get any solution?

**Comment by zion830** [comment]
I ended up deleting this library. 
But I think you can resolve it this way!
```
allprojects {
    repositories {
        google()
        jcenter() << add this line! (A warning pops up saying that 'jcenter' is deprecated.)
        ...
```

**Comment by stutijain314** [comment]
> I ended up deleting this library. But I think you can resolve it this way!
> 
> ```
> allprojects {
>     repositories {
>         google()
>         jcenter() << add this line! (A warning pops up saying that 'jcenter' is deprecated.)
>         ...
> ```

I added this. After adding this, I got more errors. Is there any other library for image slider?

**Comment by shubhamdevgupta** [comment]
getting the same issue but have not fine any solution in this how to acces this repo or how we get the full access of this repo

**Comment by Program2Builder** [comment]
I am Also Getting the same error

![image](https://github.com/user-attachments/assets/d650244d-d424-45d0-8a38-ead986ba76f9)


My Android studio version Koala-2024.1.1 Patch 1

**Comment by Program2Builder** [comment]
How Can i Resolve it

**Comment by shubhamdevgupta** [comment]
I Don't know why developer make some these type of libraries whey are not able to manage them and other dev struggling to resolve , if you have not any solution for you library so please make it private don't make it public

**Comment by misbahazmi** [comment]
> How Can i Resolve it

I made it local lib and used it. If you want, I can give the access!!!

**Comment by shubhamdevgupta** [comment]
It will be great help if you can share

**Comment by misbahazmi** [comment]
> It will be great help if you can share

Could you please try the older version: 
com.github.smarteist:autoimageslider:1.3.7-appcompat

**Comment by wahidhasyim** [comment]
please share @misbahazmi

**Comment by misbahazmi** [comment]
> please share @misbahazmi
Could you please try the older version:
com.github.smarteist:autoimageslider:1.3.7-appcompat

**Comment by deepanshu1201** [comment]
please share @misbahazmi

**Comment by misbahazmi** [comment]
> Could you please try the older version:
> com.github.smarteist:autoimageslider:1.3.7-appcompat

Could you please try the older version:
com.github.smarteist:autoimageslider:1.3.7-appcompat

**Comment by misbahazmi** [comment]
Could you please try the older version:
com.github.smarteist:autoimageslider:1.3.7-appcompat

**Comment by AnshukumarAk** [comment]
Could not GET 'https://jitpack.io/com/github/smarteist/autoimageslider/1.3.7-appcompat/autoimageslider-1.3.7-appcompat.pom'. Received status code 401 from server: Unauthorized


please anyone help me i facing this issue @misbahazmi

**Comment by deepanshu1201** [comment]
hi @AnshukumarAk  use this     implementation 'com.github.smarteist:Android-Image-Slider:1.4.0'
