### ISSUE TITLE
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.github.smarteist:autoimageslider:1.4.0.

### ISSUE THREAD

**Issue by Paridel** [smarteist/android-image-slider#219]
**Describe the bug**
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.github.smarteist:autoimageslider:1.4.0.

**To Reproduce**
No need to reproduce getting it directly now

**Expected behavior**
Find a solution to make it usable in my project.

**Screenshots**

![auto image](https://user-images.githubusercontent.com/13469408/135217802-4cb87f66-0328-4303-8bde-6bd9fa8d53ee.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version  93.0.4577.82

**Smartphone (please complete the following information):**
 - Device: Redmi Note 10 Pro
 - OS: Android 11
 - Browser Chrome
 - Version 94

**Additional context**
Just to notify that since I migrated to Gradle 7.0.2 and Android Studion Arctic 2020.3.1 Patch 2 I am having this problem where when I add the library of "com.github.smarteist:autoimageslider:1.4.0." nothing works.

**Comment by valendion** [comment]
how do you solve it ?

**Comment by AurangsEmpire** [comment]
Same issue. How to resolve?

**Comment by Paridel** [comment]
Hi
I had been able to solve the problem. I realized that the library was not recognized on mavenCetral () but rather recognized with jcenter (). And so, I added the url of jetpack.io in the settings.gradle section then when I synchronized everything was good.

See attached images.
![Settings 1](https://user-images.githubusercontent.com/13469408/144765739-52cf90b7-39a9-4579-bcae-5be157074b1c.png)

![Settings 2](https://user-images.githubusercontent.com/13469408/144765743-80db7ba1-e782-4b38-b13f-c48a2a0f5261.png)

**Comment by MohammadKaif1** [comment]
Still I can't able to implement slider View
![SliderView 2](https://user-images.githubusercontent.com/103691849/191010614-6497d9ca-c773-4e1f-9566-bc5f2fd0ffbc.png)
![sliderView](https://user-images.githubusercontent.com/103691849/191010622-1947e702-541c-42da-b065-afa1f617c318.png)

**Comment by Paridel** [comment]
@MohammadKaif1 Please see my previous answer here https://github.com/smarteist/Android-Image-Slider/issues/219#issuecomment-986308949

Make sure to add :
- jcenter()
- maven {
             url "https://jitpack.io"
         }
in the settings.gradle file as in the image present in the previous answer.

**Comment by MohammadKaif1** [comment]
I already added Jitpack url but it doesn't work .
![Uploading image_2022-09-19_182506878.png…]()

**Comment by MohammadKaif1** [comment]
I tried this as well but it doesn't work

![image_2022-09-19_182800022](https://user-images.githubusercontent.com/103691849/191022565-bfd50c57-268f-4dfa-986c-66bc068bddb2.png)

**Comment by Paridel** [comment]
Your Gradle seems to be offline. It must be activated so that it is online and will be able to download the library.

1- Click on Gradle on the right menu of Android Studio.
2- Then click on the toggle to activate it.

When it's greyed out, it's offline.
Otherwise it is online.

**In online mode :**
<img width="580" alt="Capture d’écran 2022-09-19 à 19 43 11" src="https://user-images.githubusercontent.com/13469408/191092512-af3b17cb-49ae-4f73-8fdb-e2f6378d1ba1.png">

**In offline mode :**
<img width="580" alt="Capture d’écran 2022-09-19 à 19 45 08" src="https://user-images.githubusercontent.com/13469408/191092738-bb94164f-f759-46ab-8c39-ebfb0caea7ea.png">

**Comment by MohammadKaif1** [comment]
I tried as you said but I don't know why it doesn't work.
You can also see my gradle is in online mode
![app level](https://user-images.githubusercontent.com/103691849/191177934-f78a54fc-f656-429e-8fd1-7c48795d45c4.png)
![dependencies](https://user-images.githubusercontent.com/103691849/191177937-079fa49e-17f3-4a5b-9c73-0a592b0fe1e5.png)
![dependencies2 png ](https://user-images.githubusercontent.com/103691849/191177941-3fef8b51-2bff-43bb-a2d6-7e4ad6df8956.png)
![error101](https://user-images.githubusercontent.com/103691849/191177944-eda6374b-87e0-41ea-9947-579182c81f9a.png)

**Comment by Paridel** [comment]
In the settings.gradle, you still haven't added the line **jcenter ()**

**Comment by MohammadKaif1** [comment]
Oh sorry !!
but still  after adding jcenter it doesn't work
![image_2022-09-20_121550791](https://user-images.githubusercontent.com/103691849/191186387-ba57b798-ba33-4145-8468-42e0d6d9ba2a.png)

**Comment by MohammadKaif1** [comment]
Finally I managed to solve this error . It was a silly mistake by me . By the way thanks for your support @Paridel .
