### ISSUE TITLE
have some issue in abstract SliderView class in the new update, v1.2 

### ISSUE THREAD

**Issue by ajaygosh102** [smarteist/Android-Image-Slider#22]
have some issue in abstract SliderView class in the new update, v1.2, the older version will be fine

**Comment by sedestrian** [comment]
Me too, and can't use old version because i already use glide in my project

**Comment by rockbass2560** [comment]
same error

**Comment by dsarkar99** [comment]
Same here
Please give a solution to this....

**Comment by agarwalkarag** [comment]
There is some issue in new Version (V2.2)
You can also use 
SliderView sliderView = new DefaultSliderView(getActivity());

**Comment by smarteist** [comment]
> have some issue in abstract SliderView class in the new update, v1.2, the older version will be fine

Update to 1.3.0 , and use SliderAdapter to add customized views in slider whatever you wand :+1: .
