### ISSUE TITLE
how to setvisibility slider indicator programatically?

### ISSUE THREAD

**Issue by firecatmusic** [smarteist/Android-Image-Slider#23]
when i was set the sliderLayout visibility to GONE,
the indicator won't hide too,
any solution?
![image](https://user-images.githubusercontent.com/43086018/52518108-0b5f3f80-2c78-11e9-9401-ed5f5e70d4aa.png)

**Comment by tamtom** [comment]
You can check this library https://github.com/OpenSooq/Pluto
it has the ability to have full control over your views and layout and not depending on any image library  and can disable/enable the indicator easily

**Comment by smarteist** [comment]
Checkout new version
