### ISSUE TITLE
Failed to resolve: com.github.smarteist:autoimageslider:1.4.0-appcompat

### ISSUE THREAD

**Issue by VivekSahni17** [smarteist/android-image-slider#238]
how can i solve the issue

**Comment by AmenyaZ** [comment]
check if jcenter() is missing in your build.gradle, if add it.

```
allprojects {
    repositories {
        google()
        //here
        jcenter()
        mavenCentral()
   
    }
}
```

**Comment by VivekSahni17** [comment]
Thank you! , i have already solve this issue
Your answer is  right

**Comment by Symon265** [comment]
> jcenter()

Not working for me

**Comment by VivekSahni17** [comment]
can

**Comment by VivekSahni17** [comment]
maven { url "https://jitpack.io" }
try to add this line in setting.gradle file

**Comment by Symon265** [comment]
> maven { url "https://jitpack.io" } try to add this line in setting.gradle file

No error but slider not showing its just blank

**Comment by VivekSahni17** [comment]
Temporary try to 

change height,width size  (give fix size)

**Comment by kumarsanuji12** [comment]
> Thank you! , i have already solve this issue Your answer is right

it's not solving
