### ISSUE TITLE
How to change the size of white dots?

### ISSUE THREAD

**Issue by rakib10rr3** [smarteist/Android-Image-Slider#25]

**Comment by Typ6uHa** [comment]
I open merge request with decision your problem

**Comment by tamtom** [comment]
You can check this library https://github.com/OpenSooq/Pluto
it has the ability to have full control over your views and layout and not depending on any image library  
and have full control over the indicator size

**Comment by smarteist** [comment]
> _No description provided._

Hi @rakib10rr3 , update to 1.3.0 and change indicator radius :)
