### ISSUE TITLE
Change description text color and size

### ISSUE THREAD

**Issue by usmanshad** [smarteist/Android-Image-Slider#3]
I have used the following code:

1) sliderView.setImageScaleType(ImageView.ScaleType.CENTER_CROP);
2) sliderView.setDescriptionTextColor(R.color.colorRed);
3) sliderView.setDescriptionTextSize(16);
4) sliderView.setDescription(sliderDesc[i]);

code at line 2 and 3 has no effect on the sliders. I want that code in working.

**Comment by XMAN274** [comment]
try this for color 

BLACK       = 0xFF000000;
DKGRAY      = 0xFF444444;
GRAY        = 0xFF888888;
LTGRAY      = 0xFFCCCCCC
WHITE       = 0xFFFFFFFF
RED         = 0xFFFF0000
GREEN       = 0xFF00FF00
BLUE        = 0xFF0000FF
YELLOW      = 0xFFFFFF00
CYAN        = 0xFF00FFFF
MAGENTA     = 0xFFFF00FF
TRANSPARENT = 0
and for size use something more that 16 like 20 and it will work

**Comment by tamtom** [comment]
You can check this library https://github.com/OpenSooq/Pluto
it has the ability to have full control over your views and layout
