### ISSUE TITLE
Not working for 2 slides only

### ISSUE THREAD

**Issue by mashukmashum** [smarteist/Android-Image-Slider#30]
Everything works fine if there is minimum 3 slides but it not works for 2 slides only, in this case the second slide immediately shifts without waiting.

**Comment by gkhncnr** [comment]
True.Please Help?

**Comment by edu1525** [comment]
I have the same problem here, please could anybody help?

**Comment by udongeex** [comment]
Same problem. Please check it @smarteist

**Comment by mcohen97** [comment]
I have the same problem.

**Comment by udongeex** [comment]
> I had the same problem. However, I think I have fixed it.

Thanks @mcohen97 , look like I need to add the whole library to my project to fix that.

**Comment by mcohen97** [comment]
@udongeex I am doing that too, I hope he includes my changes.

**Comment by udongeex** [comment]
It worked for me, thanks a lot @mcohen97  :D

**Comment by smarteist** [comment]
> Everything works fine if there is minimum 3 slides but it not works for 2 slides only, in this case the second slide immediately shifts without waiting.

Checkout 1.3.0 , and update to this version i fixed this issue. thank you.

**Comment by mcohen97** [comment]
You changed the whole interface, it would have been better to just accept my changes.
