### ISSUE TITLE
Clear sliderViews from SliderLayout didn't clear previous images

### ISSUE THREAD

**Issue by alvin96** [smarteist/Android-Image-Slider#32]
I want to clear slider before add another slider, but the previous image didn't clear.

```   
private fun setSliderViews(bannerArr: JsonArray) {
        if (imageSlider != null) {
            imageSlider.clearSliderViews()
        }
        val sliderView = DefaultSliderView(requireContext())

        for (i in 0 until bannerArr.size()) {
            val bannerObj = bannerArr[i].asJsonObject
            sliderView.imageUrl = bannerObj.get("image_url").asString
            

            if (imageSlider != null) {
                imageSlider.addSliderView(sliderView)
            }
        }
    }
```

**Comment by ibrha** [comment]
do you find the solution ?

**Comment by alvin96** [comment]
> do you find the solution ?

not yet

**Comment by tamtom** [comment]
You can check this library https://github.com/OpenSooq/Pluto
it has the ability to have full control over your views and layout and not depending on any image library

**Comment by alvin96** [comment]
> You can check this library https://github.com/OpenSooq/Pluto
> it has the ability to have full control over your views and layout and not depending on any image library

thank you

**Comment by mcohen97** [comment]
I Overrode this method:
 @Override
    public int getItemPosition(Object object) {
        return POSITION_NONE;
    }
in SlideAdapter, and it worked the trick.

**Comment by smarteist** [comment]
> I want to clear slider before add another slider, but the previous image didn't clear.
> 
> ```
> private fun setSliderViews(bannerArr: JsonArray) {
>         if (imageSlider != null) {
>             imageSlider.clearSliderViews()
>         }
>         val sliderView = DefaultSliderView(requireContext())
> 
>         for (i in 0 until bannerArr.size()) {
>             val bannerObj = bannerArr[i].asJsonObject
>             sliderView.imageUrl = bannerObj.get("image_url").asString
>             
> 
>             if (imageSlider != null) {
>                 imageSlider.addSliderView(sliderView)
>             }
>         }
>     }
> ```

Update to 1.3.0 , and use SliderAdapter , you can clear adapter and call notifyDataSetChanged(); it should clear sliderLayout like a charm.
