### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference com.smarteist.autoimageslider.DefaultSliderView.getView

### ISSUE THREAD

**Issue by ZeeshanArid** [smarteist/Android-Image-Slider#33]
Fatal Exception: java.lang.NullPointerException Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference com.smarteist.autoimageslider.DefaultSliderView.getView

android.view.LayoutInflater.from (LayoutInflater.java:234)
com.smarteist.autoimageslider.DefaultSliderView.getView (DefaultSliderView.java:33)
com.smarteist.autoimageslider.SliderAdapter.instantiateItem (SliderAdapter.java:54)
androidx.viewpager.widget.ViewPager.addNewItem (ViewPager.java:1010)
androidx.viewpager.widget.ViewPager.setCurrentItem (ViewPager.java:623)
com.smarteist.autoimageslider.SliderLayout$1.run (SliderLayout.java:269)
android.os.Handler.handleCallback (Handler.java:739)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1120)

**Comment by smarteist** [comment]
New version migrated to androidx checkout v1.3.0 :+1:
