### ISSUE TITLE
Time Duration for TransformAnimation

### ISSUE THREAD

**Issue by agarwalkarag** [smarteist/Android-Image-Slider#34]
How to set Time Duration for TransformAnimation in V1.2
Currently, it getting completed in millisec

**Comment by ibrha** [comment]
i think you should use 1.1.1 vers not 1.2

**Comment by smarteist** [comment]
> How to set Time Duration for TransformAnimation in V1.2
> Currently, it getting completed in millisec

updated to 1.3.1 , new version has this feature ...
