### ISSUE TITLE
Sliderview is a abstract, cannot be intantiated

### ISSUE THREAD

**Issue by Fransdiky** [smarteist/Android-Image-Slider#35]
i want to ask why my new SliderView(this) show red line and the description is "Sliderview is a abstract, cannot be intantiated"?

**Comment by agarwalkarag** [comment]
There is some issue is new Version 
You can also you use

SliderView sliderView = new DefaultSliderView(getActivity());

**Comment by smarteist** [comment]
> i want to ask why my new SliderView(this) show red line and the description is "Sliderview is a abstract, cannot be intantiated"?

Checkout 1.3.0
