### ISSUE TITLE
TypeFace!!

### ISSUE THREAD

**Issue by abolfazlfakhari** [smarteist/Android-Image-Slider#36]
Please Insert The SetTypeFace For TextView in SliderView Class.
Thanks...

**Comment by tamtom** [comment]
You can check this library https://github.com/OpenSooq/Pluto 
it has the ability to have full  control over your views and layout

**Comment by smarteist** [comment]
> Please Insert The SetTypeFace For TextView in SliderView Class.
> Thanks...

Checkout 1.3.0 , update to this release and add your custom views in SliderView...
