### ISSUE TITLE
Error inflating class com.smarteist.autoimageslider.SliderLayout

### ISSUE THREAD

**Issue by ngardue2** [smarteist/Android-Image-Slider#37]
Error inflating class com.smarteist.autoimageslider.SliderLayout

**Comment by ArslanYasin** [comment]
same issue did you find any solution?

**Comment by smarteist** [comment]
Maybe this is because of the incompatibility of the AppCompat with Androidx. new version migrated to andoridx update feedback the result .

**Comment by shipofsea** [comment]
Error inflating class com.smarteist.autoimageslider.SliderView

**Comment by gopaljain1st** [comment]
same issue 
Does anyone have a solution ?
Error inflating class com.smarteist.autoimageslider.SliderView
