### ISSUE TITLE
For weird reasons "sliderView.setImageDrawable" doesn't work for a release buidType.

### ISSUE THREAD

**Issue by MakariKevin** [smarteist/Android-Image-Slider#38]
**setImageDrawable( )** works fine with debug buildType, but displays a blank white view in a release APK. 
**setImageByte( )** seems to work but UI first freezes for like 4 sec especially when loading it from another activity.
I'm therefore left with **setImageUrl( )** as the only option.

**Comment by smarteist** [comment]
> **setImageDrawable( )** works fine with debug buildType, but displays a blank white view in a release APK.
> **setImageByte( )** seems to work but UI first freezes for like 4 sec especially when loading it from another activity.
> I'm therefore left with **setImageUrl( )** as the only option.

Checkout new version , in 1.3.0 you can create a slider adapter like recycler view, it gives you more coding flexibility to load images or adding multiple layouts in sliderview.
