### ISSUE TITLE
error when we take 2 banner on same activty.

### ISSUE THREAD

**Issue by kamalkumar13** [smarteist/Android-Image-Slider#40]
When i am taking 2 slider layout on same activity as <com.smarteist.autoimageslider.SliderLayout
            android:id="@+id/imageSliderTop"
            android:layout_width="match_parent"
            android:layout_height="match_parent"/>
and
        <com.smarteist.autoimageslider.SliderLayout
            android:id="@+id/imageSliderBottom"
            android:layout_width="match_parent"
            android:layout_height="match_parent"/>

then slider comes 1 for both.

How to resolve this issue?

**Comment by smarteist** [comment]
Tested in 1.3.0 , please update and tell me the result
