### ISSUE TITLE
Set selected item programmatically

### ISSUE THREAD

**Issue by L4grange** [smarteist/Android-Image-Slider#41]
Hello and thank you for this library!

I'm trying to implement a fullscreen image viewer when tapping the slideshow and so far I;ve got it working, but I need to set the selected item in the slideshow programmatically, so when the user changes the page in my fullscreen image view, the slide show changes as well. Is this possible?

Thank you

**Comment by smarteist** [comment]
> Hello and thank you for this library!
> 
> I'm trying to implement a fullscreen image viewer when tapping the slideshow and so far I;ve got it working, but I need to set the selected item in the slideshow programmatically, so when the user changes the page in my fullscreen image view, the slide show changes as well. Is this possible?
> 
> Thank you

Hi , updated , 1.3.1 and use         sliderView.setCurrentPagePosition(int);
method to change current page programmatically, happy coding.

**Comment by L4grange** [comment]
Perfect, thank you very much!
