### ISSUE TITLE
Error inflating class com.smarteist.autoimageslider.SliderView

### ISSUE THREAD

**Issue by GTAexcess** [smarteist/Android-Image-Slider#42]
Hi
Error inflating class com.smarteist.autoimageslider.SliderView

**Comment by mepunit** [comment]
Same problem. :-/

@GTAexcess: did you find any solution?

**Comment by MohamedHamole7** [comment]
same problem :(

**Comment by MohamedHamole7** [comment]
did you know how to fix this issue please?
@smarteist 
 Binary XML file line #61: Error inflating class com.smarteist.autoimageslider.SliderView

**Comment by M3GlamCode** [comment]
I have the same issue. Please assist.

**Comment by Kapilyadav721** [comment]
The Problem arose due to backward compatibility of this library with older android....It keeps crash till android 7
