### ISSUE TITLE
Turn of over scrolling

### ISSUE THREAD

**Issue by bemrePG** [smarteist/Android-Image-Slider#43]
Hi Ali Hosseini,

I really appreciate your great work. 
Just have a short question. 
Is there a way to stop scrolling to a direction when there is no image and the view jumps to the first image?
E.g. there are 3 images and my current position is the third one. So when i am tryin to scroll on. It jumps to the first image.

Thanks.

Best regards

**Comment by smarteist** [comment]
> Hi Ali Hosseini,
> 
> I really appreciate your great work.
> Just have a short question.
> Is there a way to stop scrolling to a direction when there is no image and the view jumps to the first image?
> E.g. there are 3 images and my current position is the third one. So when i am tryin to scroll on. It jumps to the first image.
> 
> Thanks.
> 
> Best regards

Hi , If i understand correctly, you want to disable circular behavior of slider view ... you can disable it by using this method like this:
`sliderView.setCircularHandlerEnabled(false);` 
or if you want to handle autocycle by your own strategy don't call startAutoCycle and set currentPageListener and handle it with your custom scenario...

**Comment by smarteist** [comment]
> Hi Ali Hosseini,
> 
> I really appreciate your great work.
> Just have a short question.
> Is there a way to stop scrolling to a direction when there is no image and the view jumps to the first image?
> E.g. there are 3 images and my current position is the third one. So when i am tryin to scroll on. It jumps to the first image.
> 
> Thanks.
> 
> Best regards

Updated 1.3.2

**Comment by bemrePG** [comment]
Hi,

thanks. But now it can't resolve setSliderIndicatorUnselectedColor and setSliderIndicatorSelectedColor.

**Comment by smarteist** [comment]
Some Method names changed, please change it .

**Comment by DavidMueller1** [comment]
I'm using Version 1.4.0 and the method setCircularHandlerEnabled does not exist in SliderView. Can't find anything similar either. Did you rename/remove it? Thanks in advance <3
