### ISSUE TITLE
how to use without androidx?

### ISSUE THREAD

**Issue by huyvm** [smarteist/Android-Image-Slider#45]
I cannot use adapt. It's rise an error: setSliderAdapter (androidx.viewpaper.widget.PaperAdapter) in SliderView cannot be applied to ...

**Comment by smarteist** [comment]
Unfortunately this library and many more libraries migrated to jetpack androidx components, you can refactor your project easily to androidx by using latest version of android studio... Search for how to refactor project to androidx

**Comment by huyvm** [comment]
@smarteist okay, i migrated to androidx. Thanks so much for your support.

**Comment by huyvm** [comment]
i get some errors when migrate to androidx. Some libs not work. You can checkout new branch without androidx?
