### ISSUE TITLE
Handle Click Event on sliderView

### ISSUE THREAD

**Issue by sharma-kunal** [smarteist/Android-Image-Slider#46]
Hello Ali Hosseini,

Thank you for such a wonderful library. I really appreciate your work.

I am a beginner in android and learnt about your library. I have implemented the Image Slider using your tutorial but I don't know how can I handle Click events on the Image ?

**Comment by smarteist** [comment]
You have an instance of parent view in viewHolder class (it can be accessed in onBindViewHolder method by field declaration), so you can set on click listener for views separately...

**Comment by sharma-kunal** [comment]
Can you please elaborate a little.

**Comment by sharma-kunal** [comment]
Can you please elaborate a little.

**Comment by smarteist** [comment]
Suppose your Holder class is like so:
```
class SliderAdapterVH extends SliderViewAdapter.ViewHolder {

        public View itemView;
        ImageView imageViewBackground;
        ImageView imageGifContainer;
        TextView textViewDescription;

        public SliderAdapterVH(View itemView) {
            super(itemView);
            imageViewBackground = itemView.findViewById(R.id.iv_auto_image_slider);
            imageGifContainer = itemView.findViewById(R.id.iv_gif_container);
            textViewDescription = itemView.findViewById(R.id.tv_auto_image_slider);
            this.itemView = itemView;
        }
    }
```
The `itemView` object is parent view of each item, so you can set the click listener on this object.
This is exactly the same as the implementation of recyclerView.

**Comment by kannasaikiran** [comment]
In your adapter just copy this)

// lets thinl the adapterName is SlideAdapter

`    // lets think the adapterName is SlideAdapter so create the variable
    private SliderAdapter.OnItemClickListener mListener;

    // lets create the interface for onclicks
    public interface OnItemClickListener {
        void onItemClick(int position);}

    // lets create the set onclick method 
    public void setOnItemClickListener(SliderAdapter.OnItemClickListener listener) {
        mListener = listener; }

        // in onbindViewHolder
    @Override
    public void onBindViewHolder(Holder viewHolder, int position) {
        // most of the time the slider is made of imageview so on the imageview click 
        viewHolder.imageView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if (mListener != null) {
                    if (position != RecyclerView.NO_POSITION) {
                        mListener.onItemClick(position);
                    }
                }
            }
        });
        
    }`

**In Main Activity, use your Adapter for Onclick**

`sliderAdapter.setOnItemClickListener(new SliderAdapter.OnItemClickListener() {
            @Override
            public void onItemClick(int position) {
                String p = String.valueOf(position);
                Toast.makeText(getContext(), p, Toast.LENGTH_SHORT).show();
    }
});`


**We can get the position of the clicked item**
