### ISSUE TITLE
Error getCount() java.lang.NullPointerException

### ISSUE THREAD

**Issue by huyvm** [smarteist/Android-Image-Slider#47]
Hi, have an error when run app. It's rise "java.lang.NullPointerException: Attempt to invoke virtual method 'int androidx.viewpager.widget.PagerAdapter.getCount()' on a null object reference at com.smarteist.autoimageslider.SliderView$2.run(SliderView.java:397)..."

**Comment by smarteist** [comment]
> Hi, have an error when run app. It's rise "java.lang.NullPointerException: Attempt to invoke virtual method 'int androidx.viewpager.widget.PagerAdapter.getCount()' on a null object reference at com.smarteist.autoimageslider.SliderView$2.run(SliderView.java:397)..."

always call method notifyDataSetChanged() method when adapter data is changed.

**Comment by huyvm** [comment]
Hi, thanks for your response. But, it's still not work. It's rise more errors. "java.lang.NullPointerException: Attempt to invoke virtual method 'void adapter.notifyDataSetChanged()' on a null object reference" in updateView

**Comment by smarteist** [comment]
> Hi, thanks for your response. But, it's still not work. It's rise more errors. "java.lang.NullPointerException: Attempt to invoke virtual method 'void adapter.notifyDataSetChanged()' on a null object reference" in updateView

Because the slider adapter is null there. first set adapter to sliderview then update your views.

**Comment by huyvm** [comment]
Yep, i'm set adapter in initView, and notifyDataSetChanged in updateView. But, it's still rise errors

**Comment by huyvm** [comment]
done. It worked for me. Thanks so much
