### ISSUE TITLE
Problem in transition with 2 images

### ISSUE THREAD

**Issue by Nicolas2106** [smarteist/android-image-slider#5]
Transition doesn't behave correctly when there are only 2 images: the second image is displayed for too short time.

**Comment by venky97vp** [comment]
I solved the issue. Check this link
https://github.com/smarteist/android-image-slider/pull/6#issue-210848091

**Comment by Nicolas2106** [comment]
venky97vp solved this issue.
Dowload zip file from https://github.com/venky97vp/android-image-slider/tree/bugfix-twoimages and import into your project.

**Comment by Pragatheesh** [comment]
Hi @Nicolas2106 its much unclear, using com.github.smarteist:autoimageslider:1.2.0 the issue still exists.

Do you mean to manually manage the dependency by importing the zip from the provided link?
