### ISSUE TITLE
method not override from its super class?

### ISSUE THREAD

**Issue by MrRoot313** [smarteist/Android-Image-Slider#50]
@Override     public int getCount() {} 
this method is not override from its super class ...

**Comment by SubhaSarkar** [comment]
I'm facing the same problem too.

**Comment by SubhaSarkar** [comment]
> @override public int getCount() {}
> this method is not override from its super class ...

migrate to androidx

**Comment by Izudinalqasam** [comment]
can you show me what do the dependencies look like?
