### ISSUE TITLE
VH extends ViewHolder declared in class SliderViewAdapter

### ISSUE THREAD

**Issue by MrRoot313** [smarteist/Android-Image-Slider#52]
error: type argument SliderAdapterExample.SliderAdapterVHClass is not within bounds of type-variable VH
where VH is a type-variable:
VH extends ViewHolder declared in class SliderViewAdapter

**Comment by AhmedSaberAfaqy** [comment]
i have the same problem
how did you fix it ?

**Comment by aqibshxhzd** [comment]
@AhmedSaberAfaqy  you need to migrate at Androidx
