### ISSUE TITLE
SliderView was not registered

### ISSUE THREAD

**Issue by HagosAlema** [smarteist/Android-Image-Slider#55]
I am getting the following error, when I try to open another activity which uses sliderview from an activity that uses sliderview too

IllegalStateException: Observer com.smarteist.autoimageslider.SliderView$1@1cdc833 was not registered.

**Comment by smarteist** [comment]
> I am getting the following error, when I try to open another activity which uses sliderview from an activity that uses sliderview too
> 
> IllegalStateException: Observer com.smarteist.autoimageslider.SliderView$1@1cdc833 was not registered.

Hi , which version of the library do you use? if it's 1.3.2 and you still get this error please clear gradle cache and rebuild your project. please take a look at this issue [Here](https://github.com/smarteist/Android-Image-Slider/issues/49)

**Comment by HagosAlema** [comment]
I was using version 1.3.1. I updated it to the latest version and it worked.  
Thank you!
