### ISSUE TITLE
This is not an issue!!! want to use this  with android rather than androidx

### ISSUE THREAD

**Issue by darpanrajput** [smarteist/Android-Image-Slider#57]
i wanted to use this project without androix  but this lib is made using androidx support.
this because i have came so far with my project and there are so many lib and i can't bear any bugs/ error by importing the project at androidx because there are so many third party library that i use which is not made on androidx so what i did i clone your project ,remove the pakage name,change the androidx to android  and created the AAR file to be used in my project without androidx support . now i want you to take this  project from me and publish it at your repo as jar
so that it can be accessible to all who want to use it without androidx.

but i don't know how to contact you or how i  can it to give you ..
and thanks again for this amazing lib

**Comment by smarteist** [comment]
> i wanted to use this project without androix but this lib is made using androidx support.
> this because i have came so far with my project and there are so many lib and i can't bear any bugs/ error by importing the project at androidx because there are so many third party library that i use which is not made on androidx so what i did i clone your project ,remove the pakage name,change the androidx to android and created the AAR file to be used in my project without androidx support . now i want you to take this project from me and publish it at your repo as jar
> so that it can be accessible to all who want to use it without androidx.
> 
> but i don't know how to contact you or how i can it to give you ..
> and thanks again for this amazing lib

Hi darpan, you can include library source in your project and refactor it to support library, take a look at this [adding-library-source-into-android-studio](https://stackoverflow.com/questions/34380497/adding-library-source-into-android-studio)
and here [undo-migration-to-androidx](https://stackoverflow.com/questions/53446801/undo-migration-to-androidx)

**Comment by smarteist** [comment]
`implementation 'com.github.smarteist:autoimageslider:1.3.2-appcompat'`
app compat version is now available.
