### ISSUE TITLE
1.2.0 how to programmatically set slider page    

### ISSUE THREAD

**Issue by sharadir** [smarteist/Android-Image-Slider#62]
we use version 1.2.0, and did not find a way to move slider images programmatically (our app is installed on android TV using remote control actions)
bdw, I've seen version 1.3.2 has the option to set a page, the problem is the code example in the readme file is not even compiling. so we stay with 1.2.0 for now

**Comment by smarteist** [comment]
> we use version 1.2.0, and did not find a way to move slider images programmatically (our app is installed on android TV using remote control actions)
> bdw, I've seen version 1.3.2 has the option to set a page, the problem is the code example in the readme file is not even compiling. so we stay with 1.2.0 for now

If you are using appcompat libraries use this version :
`implementation 'com.github.smarteist:autoimageslider:1.3.2-appcompat'`
