### ISSUE TITLE
space between slider images

### ISSUE THREAD

**Issue by Zia-Sheikh** [smarteist/Android-Image-Slider#72]
Hello smartiest, thanks for the work you do it's just awesome. But i am facing difficulty while giving space between slider images, i.e., when image 1 is slide then how to give space b/w image 1 and 2 ? is there a way? please guide, thanks.
**Your help would be much appreciated.**

**Comment by smarteist** [comment]
> Hello smartiest, thanks for the work you do it's just awesome. But i am facing difficulty while giving space between slider images, i.e., when image 1 is slide then how to give space b/w image 1 and 2 ? is there a way? please guide, thanks.
> **Your help would be much appreciated.**

Thank you, set a margin for ImageView inside your slider item , you can achieve this by this way if i understand it correctly.

**Comment by smarteist** [comment]
> Hello smartiest, thanks for the work you do it's just awesome. But i am facing difficulty while giving space between slider images, i.e., when image 1 is slide then how to give space b/w image 1 and 2 ? is there a way? please guide, thanks.
> **Your help would be much appreciated.**

Thank you, set a margin for ImageView inside your slider item , you can achieve it in this way if i understand it correctly.
