### ISSUE TITLE
Slider issue

### ISSUE THREAD

**Issue by samerhamdani01** [smarteist/Android-Image-Slider#74]
in case slider has 2 images (image1 , image2) once image2 appears it automatically slides back to image1 without waiting for the delay.
This issue doesn't occurs when slider has more than 2 images.
Any suggestion please ? Thank you

**Comment by tempdevexioms** [comment]
I am facing the same issue

**Comment by smarteist** [comment]
> in case slider has 2 images (image1 , image2) once image2 appears it automatically slides back to image1 without waiting for the delay.
> This issue doesn't occurs when slider has more than 2 images.
> Any suggestion please ? Thank you

What version are you using right now? If you are using the latest version give more information please.

**Comment by illyaevseev** [comment]
Ver: 1.2.0

In Fragment:

`binding.gallery.setAutoScrolling(false);`

`viewModel.entity.observe(getViewLifecycleOwner(), entity -> {
            for(Entity photo : entity.getPhotos()){
                SliderView sliderView = new DefaultSliderView(getContext());
                sliderView.setImageUrl(photo.getPath());
                sliderView.setImageScaleType(ImageView.ScaleType.FIT_CENTER);
                sliderView.setDescription("");
                binding.gallery.addSliderView(sliderView);
            }
        });`

In XML trivial SliderLayout with constraints

**Comment by smarteist** [comment]
> Ver: 1.2.0
> 
> In Fragment:
> 
> `binding.gallery.setAutoScrolling(false);`
> 
> `viewModel.entity.observe(getViewLifecycleOwner(), entity -> { for(Entity photo : entity.getPhotos()){ SliderView sliderView = new DefaultSliderView(getContext()); sliderView.setImageUrl(photo.getPath()); sliderView.setImageScaleType(ImageView.ScaleType.FIT_CENTER); sliderView.setDescription(""); binding.gallery.addSliderView(sliderView); } });`
> 
> In XML trivial SliderLayout with constraints

Please update to `1.3.4`
