### ISSUE TITLE
Add on click listener for images clicked

### ISSUE THREAD

**Issue by UsamaAltaf** [smarteist/Android-Image-Slider#78]
how to add onclicklistener on images

**Comment by avecost** [comment]
Hello you do it inside adapter; example:

`   
   @Override
    public void onBindViewHolder(SliderAdapterVH viewHolder, final int position) {

        viewHolder.itemView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Toast.makeText(context, "I was click " + position, Toast.LENGTH_SHORT).show();
            }
        });

        Glide.with(viewHolder.itemView)
                .load(urls[position])
                .into(viewHolder.imageViewBackground);
    }`
