### ISSUE TITLE
IndicatorSliderMargin

### ISSUE THREAD

**Issue by FirmanMFK** [smarteist/Android-Image-Slider#79]
Hello @smarteist Is it possible to make sliderIndicatorMargin different in the margins, for example sliderIndicatorMarginLeft = "16" or sliderIndicatorMarginRight = "18"?
Thank you

**Comment by FirmanMFK** [comment]
Hello @smarteist Is it possible to make sliderIndicatorMargin different in the margins, for example sliderIndicatorMarginLeft = "16" or sliderIndicatorMarginRight = "18"?
Thank you

**Comment by sarankumar-ns** [comment]
Possible by replacing the src code with what you need.

https://github.com/smarteist/Android-Image-Slider/blob/de6f29fe702d77d7d7d1c24cad0e1a0e759ef9ef/autoimageslider/src/main/java/com/smarteist/autoimageslider/SliderView.java#L470

layoutParams.setMargins(left, top, right, bottom);

**Comment by sarankumar-ns** [comment]
Now this is possible
