### ISSUE TITLE
slider overlay effect

### ISSUE THREAD

**Issue by iAnannaRahman** [smarteist/Android-Image-Slider#8]
Hello, Currently I am using your slider library in one of my apps. And I am facing some problems 
1.  app:defaultIndicators="square" can't use this function on this slider 

2. And most Importantly, I want to make the slider Effect to be white or transparent. what I am saying is, in this slider the bottom is getting blurred by black shading. I want to remove that shade or make that shade to white shading.
How can I do that? please, suggest...

![slider effect](https://user-images.githubusercontent.com/42947094/46058240-e7dda180-c17b-11e8-9f22-2e534550306c.PNG)

**Comment by Deepak111992** [comment]
have you found something?

**Comment by tamtom** [comment]
You can check this library https://github.com/OpenSooq/Pluto
it has the ability to have full control over your views and layout and many specs of indicator

**Comment by smarteist** [comment]
> Hello, Currently I am using your slider library in one of my apps. And I am facing some problems
> 
> 1. app:defaultIndicators="square" can't use this function on this slider
> 2. And most Importantly, I want to make the slider Effect to be white or transparent. what I am saying is, in this slider the bottom is getting blurred by black shading. I want to remove that shade or make that shade to white shading.
>    How can I do that? please, suggest...
> 
> ![slider effect](https://user-images.githubusercontent.com/42947094/46058240-e7dda180-c17b-11e8-9f22-2e534550306c.PNG)

Checkout 1.3.0

**Comment by AmirMehr** [comment]
I changed SliderAdapter.java
`
public class SliderAdapter extends SliderViewAdapter<SliderAdapter.SliderAdapterVH> {

    private Context context;
    private List<SliderItem> mSliderItems = new ArrayList<>();
    private boolean withBottomGradient;

    public SliderAdapter (Context context, boolean withBottomGradient) {
        this.withBottomGradient = withBottomGradient;
        this.context = context;
    }

    public void renewItems(List<SliderItem> sliderItems) {
        this.mSliderItems = sliderItems;
        notifyDataSetChanged();
    }

    public void deleteItem(int position) {
        this.mSliderItems.remove(position);
        notifyDataSetChanged();
    }

    public void addItem(SliderItem sliderItem) {
        this.mSliderItems.add(sliderItem);
        notifyDataSetChanged();
    }

    @Override
    public SliderAdapterVH onCreateViewHolder(ViewGroup parent) {
        View inflate = LayoutInflater.from(parent.getContext()).inflate(R.layout.image_slider_layout_item, null);
        FrameLayout bottomGradient = inflate.findViewById(R.id.fl_shadow_container);
        if(!withBottomGradient){
            bottomGradient.setBackgroundResource(0);
        }
        return new SliderAdapterVH(inflate);
    }

    @Override
    public void onBindViewHolder(SliderAdapterVH viewHolder, final int position) {

        SliderItem sliderItem = mSliderItems.get(position);

        viewHolder.textViewDescription.setText(sliderItem.getText());
        viewHolder.textViewDescription.setTextSize(16);
        viewHolder.textViewDescription.setTextColor(Color.WHITE);
        CircularProgressDrawable circularProgressDrawable = new CircularProgressDrawable(context);
        circularProgressDrawable.setStrokeWidth(5f);
        circularProgressDrawable.setCenterRadius(30f);
        circularProgressDrawable.setColorSchemeColors(context.getResources().getColor(R.color.colorGray));
        circularProgressDrawable.start();
        Glide.with(viewHolder.itemView)
        .load(sliderItem.getImage()).apply(new RequestOptions()
                .placeholder(circularProgressDrawable)
                .fitCenter())
        .fitCenter()
        .into(viewHolder.imageViewBackground);

        viewHolder.itemView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
               // Toast.makeText(context, "This is item in position " + position, Toast.LENGTH_SHORT).show();
            }
        });
    }

    @Override
    public int getCount() {
            //slider view count could be dynamic size
            return mSliderItems.size();
            }

    class SliderAdapterVH extends SliderViewAdapter.ViewHolder {

        View itemView;
        ImageView imageViewBackground;
        ImageView imageGifContainer;
        TextView textViewDescription;

        public SliderAdapterVH(View itemView) {
            super(itemView);
            imageViewBackground = itemView.findViewById(R.id.iv_auto_image_slider);
            imageGifContainer = itemView.findViewById(R.id.iv_gif_container);
            textViewDescription = itemView.findViewById(R.id.tv_auto_image_slider);
            this.itemView = itemView;
        }
    }

}`
