### ISSUE TITLE
Missing placeholder in glide

### ISSUE THREAD

**Issue by karagarwal** [smarteist/Android-Image-Slider#9]
Hello your Library is working fine but it has missing placeholder image functionality in glide 
SliderView.java line 152, 155
Please add 
.apply(new RequestOptions().placeholder(placeholderImageDrawable))

Because of missing Placeholder if image at the specified URL doesn't exist it will show blank screen

**Comment by tamtom** [comment]
You can check this library https://github.com/OpenSooq/Pluto
it has the ability to have full control over your views and layout and changing the placeholder is easy
