### ISSUE TITLE
Regulate scroll time if you use video in slide

### ISSUE THREAD

**Issue by nikolacrnicrni** [smarteist/Android-Image-Slider#93]
I am trying to use VideoView in adapter and I successfully added all the videos, but they are different length, so I can't set fixed time, I need to have time of the video same as scroll time. I could not found the way to do that.

Is there any way?

**Comment by smarteist** [comment]
> I am trying to use VideoView in adapter and I successfully added all the videos, but they are different length, so I can't set fixed time, I need to have time of the video same as scroll time. I could not found the way to do that.
> 
> Is there any way?

You should implement your own sliding timer, turn off autoSliding by passing a `false` arg, then call `slideToNextPosition()` manually.
