### ISSUE TITLE
Cannot be used in fragment

### ISSUE THREAD

**Issue by chenbazhu** [smarteist/Android-Image-Slider#96]
I can use it normally in activity, but not in fragment. I found that neither oncreateviewholder nor onbindviewholder was called in slideradapterexample. What should I do?

**Comment by chenbazhu** [comment]
The problem has been solved. Please forgive me for being a beginner

**Comment by venkyvc** [comment]
May i know how you solved the problem cause I'm also facing the same.

**Comment by saha-pallabi** [comment]
I had applied earlier both in activity and fragment, I hadn't faced any issue. But for the current version of android SDK after added navigation and using under fragment, the library suddenly not getting recognized and showing the error as "class referred in layout was not found in project". Kindly suggest
