### ISSUE TITLE
Actual Cycling and Direction Change

### ISSUE THREAD

**Issue by AlmutawaEssam** [smarteist/Android-Image-Slider#98]
Hello,
Thank you for providing us this library that saved me a lot of work.
I'm looking for making the slide continues when it reaches the last item, not like what is is happening like now
Example
Size is: 3
Now: 1 -> 2 -> 3 -> 2 -> 1 
What I'm suggesting is: 1 -> 2 -> 3 -> 1
So the user won't feel going back to the first item going through all the previous items.
Also, I'm looking to have a variable that decide the start direction and the slide direction
which means if first item is on the left and the slide is to left or first item is on the right and the slide is to right.

**Comment by smarteist** [comment]
update to 1.3.4

**Comment by hissaan** [comment]
@smarteist how to stop cycling when we reach the last item in the slider.

**Comment by smarteist** [comment]
> @smarteist how to stop cycling when we reach the last item in the slider.

You can use android view pager for achieve that.

**Comment by smarteist** [comment]
> @smarteist how to stop cycling when we reach the last item in the slider.

Its now available in ```1.3.6```. you can pass infiniteAdapter=false in ```setAdapter``` method.
