### ISSUE TITLE
How to use this in fragment

### ISSUE THREAD

**Issue by venkyvc** [smarteist/Android-Image-Slider#99]
I tried using auto image slider in my fragment passing the context as getactivity(); when app runs it stops working and throws null pointer exception and when used getcontext(); same thing happens I want to know how can I access it into the fragment

**Comment by smarteist** [comment]
Update to `1.3.4` , i've tested in fragments and it works properly.

**Comment by venkyvc** [comment]
Okay what context should I pass when the code is return inside the fragment activity.
